/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Filereading.ExcelManager;

/**
 *
 * @author Sofia
 */

/*
0 = duracion de dias
1 = deadline 
2 = ensambladores 
3 =placa base
4 =  cpu 
5 = ram 
6 = fuente 
7 = tarjetas 
*/


public class BothGUI extends javax.swing.JFrame {
    /**
     * Creates new form BothGUI
     */
    public BothGUI() {
        initComponents();
        ExcelManager manager = new ExcelManager(); 
        int [] base = {0}; 
        int [] apple = new int [6]; 
        //Empresa Apple (Sofia)
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        downmbapple = new javax.swing.JButton();
        upmbapple = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ramapple = new javax.swing.JTextField();
        downramapple = new javax.swing.JButton();
        upramapple = new javax.swing.JButton();
        powerapple = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        uppowerapple = new javax.swing.JButton();
        downpowerapple = new javax.swing.JButton();
        upcpuapple = new javax.swing.JButton();
        downcpuapple = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cpuapple = new javax.swing.JTextField();
        graphicapple = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        upgraphicapple = new javax.swing.JButton();
        downgraphicapple = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        assemapple = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        upassemapple = new javax.swing.JButton();
        downassemapple = new javax.swing.JButton();
        jProgressBar6 = new javax.swing.JProgressBar();
        mbapple = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        downmbdell = new javax.swing.JButton();
        upmbdell = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ramdell = new javax.swing.JTextField();
        downramdell = new javax.swing.JButton();
        upramdell = new javax.swing.JButton();
        powerdell = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        uppowerdell = new javax.swing.JButton();
        downpowerdell = new javax.swing.JButton();
        upcpudell = new javax.swing.JButton();
        downcpudell = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cpudell = new javax.swing.JTextField();
        graphicdell = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        upgraphicdell = new javax.swing.JButton();
        downgraphicdell = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        jProgressBar8 = new javax.swing.JProgressBar();
        jProgressBar9 = new javax.swing.JProgressBar();
        jProgressBar10 = new javax.swing.JProgressBar();
        jProgressBar11 = new javax.swing.JProgressBar();
        assemdell = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        upassemdell = new javax.swing.JButton();
        downassemadell = new javax.swing.JButton();
        jProgressBar12 = new javax.swing.JProgressBar();
        mbdell = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField51 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ready 💻");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField2.setFocusable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 95, 30, 30));

        downmbapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downmbapple.setText("▼");
        downmbapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downmbappleActionPerformed(evt);
            }
        });
        jPanel5.add(downmbapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 20));

        upmbapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upmbapple.setText("▲");
        upmbapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upmbappleActionPerformed(evt);
            }
        });
        jPanel5.add(upmbapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 70, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RAM Memory");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        ramapple.setEditable(false);
        ramapple.setBackground(new java.awt.Color(255, 255, 255));
        ramapple.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ramapple.setForeground(new java.awt.Color(51, 51, 51));
        ramapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ramapple.setText("0");
        ramapple.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        ramapple.setFocusable(false);
        ramapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramappleActionPerformed(evt);
            }
        });
        jPanel5.add(ramapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 95, 30, 30));

        downramapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downramapple.setText("▼");
        downramapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downramappleActionPerformed(evt);
            }
        });
        jPanel5.add(downramapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 70, 20));

        upramapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upramapple.setText("▲");
        upramapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upramappleActionPerformed(evt);
            }
        });
        jPanel5.add(upramapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 70, 20));

        powerapple.setEditable(false);
        powerapple.setBackground(new java.awt.Color(255, 255, 255));
        powerapple.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        powerapple.setForeground(new java.awt.Color(51, 51, 51));
        powerapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        powerapple.setText("0");
        powerapple.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        powerapple.setFocusable(false);
        powerapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerappleActionPerformed(evt);
            }
        });
        jPanel5.add(powerapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 145, 30, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Power suply");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 40));

        uppowerapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uppowerapple.setText("▲");
        uppowerapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppowerappleActionPerformed(evt);
            }
        });
        jPanel5.add(uppowerapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 20));

        downpowerapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downpowerapple.setText("▼");
        downpowerapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downpowerappleActionPerformed(evt);
            }
        });
        jPanel5.add(downpowerapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, 20));

        upcpuapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upcpuapple.setText("▲");
        jPanel5.add(upcpuapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 70, 20));

        downcpuapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downcpuapple.setText("▼");
        jPanel5.add(downcpuapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, 20));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CPUs");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 40));

        cpuapple.setEditable(false);
        cpuapple.setBackground(new java.awt.Color(255, 255, 255));
        cpuapple.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cpuapple.setForeground(new java.awt.Color(51, 51, 51));
        cpuapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpuapple.setText("0");
        cpuapple.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        cpuapple.setFocusable(false);
        jPanel5.add(cpuapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 195, 30, 30));

        graphicapple.setEditable(false);
        graphicapple.setBackground(new java.awt.Color(255, 255, 255));
        graphicapple.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        graphicapple.setForeground(new java.awt.Color(51, 51, 51));
        graphicapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        graphicapple.setText("0");
        graphicapple.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        graphicapple.setFocusable(false);
        jPanel5.add(graphicapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 245, 30, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Graphic Card");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 40));

        upgraphicapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upgraphicapple.setText("▲");
        jPanel5.add(upgraphicapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 70, 20));

        downgraphicapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downgraphicapple.setText("▼");
        jPanel5.add(downgraphicapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 70, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Type of Worker");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel5.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, 20));
        jPanel5.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 100, 20));
        jPanel5.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, 20));
        jPanel5.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 100, 20));
        jPanel5.add(jProgressBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 100, 20));

        assemapple.setEditable(false);
        assemapple.setBackground(new java.awt.Color(255, 255, 255));
        assemapple.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        assemapple.setForeground(new java.awt.Color(51, 51, 51));
        assemapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        assemapple.setText("0");
        assemapple.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        assemapple.setFocusable(false);
        jPanel5.add(assemapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 295, 30, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Assemblers");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 40));

        upassemapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upassemapple.setText("▲");
        jPanel5.add(upassemapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, 20));

        downassemapple.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downassemapple.setText("▼");
        jPanel5.add(downassemapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, 20));
        jPanel5.add(jProgressBar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 100, 20));

        mbapple.setEditable(false);
        mbapple.setBackground(new java.awt.Color(255, 255, 255));
        mbapple.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        mbapple.setForeground(new java.awt.Color(51, 51, 51));
        mbapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mbapple.setText("0");
        mbapple.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        mbapple.setFocusable(false);
        mbapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbappleActionPerformed(evt);
            }
        });
        jPanel5.add(mbapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 45, 30, 30));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(51, 51, 51));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jTextField10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField10.setFocusable(false);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 45, 30, 30));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(51, 51, 51));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");
        jTextField12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField12.setFocusable(false);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 145, 30, 30));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(51, 51, 51));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("0");
        jTextField13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField13.setFocusable(false);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 245, 30, 30));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(51, 51, 51));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0");
        jTextField14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField14.setFocusable(false);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 195, 30, 30));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(51, 51, 51));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("0");
        jTextField15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField15.setFocusable(false);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 195, 30, 30));

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(255, 255, 255));
        jTextField18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(51, 51, 51));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("0");
        jTextField18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField18.setFocusable(false);
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 45, 30, 30));

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(255, 255, 255));
        jTextField19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(51, 51, 51));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("0");
        jTextField19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField19.setFocusable(false);
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 95, 30, 30));

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(255, 255, 255));
        jTextField20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(51, 51, 51));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("0");
        jTextField20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField20.setFocusable(false);
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 145, 30, 30));

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(255, 255, 255));
        jTextField21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(51, 51, 51));
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("0");
        jTextField21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField21.setFocusable(false);
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 195, 30, 30));

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(255, 255, 255));
        jTextField22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(51, 51, 51));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("0");
        jTextField22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField22.setFocusable(false);
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 245, 30, 30));

        jTextField23.setEditable(false);
        jTextField23.setBackground(new java.awt.Color(255, 255, 255));
        jTextField23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(51, 51, 51));
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("0");
        jTextField23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField23.setFocusable(false);
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 295, 30, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Max");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Standard");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 80, 40));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 80, 30));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Standard");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 80, 40));

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(0, 0, 0));
        jTextField17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("0");
        jTextField17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField17.setFocusable(false);
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 80, 30));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Type of Worker");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Motherboard");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 40));

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(255, 255, 255));
        jTextField25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField25.setForeground(new java.awt.Color(51, 51, 51));
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText("0");
        jTextField25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField25.setFocusable(false);
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 295, 30, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Warehouse");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 580, 340));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Project Manager");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 40));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("....");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField3.setFocusable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 40));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(51, 51, 51));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField11.setFocusable(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 70, 40));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Fouls");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 70, 40));

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(255, 255, 255));
        jTextField26.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField26.setForeground(new java.awt.Color(51, 51, 51));
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setText("0");
        jTextField26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField26.setFocusable(false);
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 120, 40));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Discounted");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 120, 40));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Proyect Manager");
        jLabel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 150, 40));

        jTextField27.setEditable(false);
        jTextField27.setBackground(new java.awt.Color(255, 255, 255));
        jTextField27.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField27.setForeground(new java.awt.Color(51, 51, 51));
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText("....");
        jTextField27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField27.setFocusable(false);
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 580, 160));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, 640, 580));

        jPanel3.setBackground(new java.awt.Color(157, 200, 222));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ready 💻");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jTextField28.setEditable(false);
        jTextField28.setBackground(new java.awt.Color(255, 255, 255));
        jTextField28.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField28.setForeground(new java.awt.Color(51, 51, 51));
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setText("0");
        jTextField28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField28.setFocusable(false);
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 95, 30, 30));

        downmbdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downmbdell.setText("▼");
        downmbdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downmbdellActionPerformed(evt);
            }
        });
        jPanel7.add(downmbdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 20));

        upmbdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upmbdell.setText("▲");
        upmbdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upmbdellActionPerformed(evt);
            }
        });
        jPanel7.add(upmbdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 70, 20));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("RAM Memory");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        ramdell.setEditable(false);
        ramdell.setBackground(new java.awt.Color(255, 255, 255));
        ramdell.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ramdell.setForeground(new java.awt.Color(51, 51, 51));
        ramdell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ramdell.setText("0");
        ramdell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        ramdell.setFocusable(false);
        ramdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramdellActionPerformed(evt);
            }
        });
        jPanel7.add(ramdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 95, 30, 30));

        downramdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downramdell.setText("▼");
        downramdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downramdellActionPerformed(evt);
            }
        });
        jPanel7.add(downramdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 70, 20));

        upramdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upramdell.setText("▲");
        upramdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upramdellActionPerformed(evt);
            }
        });
        jPanel7.add(upramdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 70, 20));

        powerdell.setEditable(false);
        powerdell.setBackground(new java.awt.Color(255, 255, 255));
        powerdell.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        powerdell.setForeground(new java.awt.Color(51, 51, 51));
        powerdell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        powerdell.setText("0");
        powerdell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        powerdell.setFocusable(false);
        powerdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerdellActionPerformed(evt);
            }
        });
        jPanel7.add(powerdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 145, 30, 30));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Power suply");
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 40));

        uppowerdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uppowerdell.setText("▲");
        uppowerdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppowerdellActionPerformed(evt);
            }
        });
        jPanel7.add(uppowerdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 20));

        downpowerdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downpowerdell.setText("▼");
        downpowerdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downpowerdellActionPerformed(evt);
            }
        });
        jPanel7.add(downpowerdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, 20));

        upcpudell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upcpudell.setText("▲");
        jPanel7.add(upcpudell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 70, 20));

        downcpudell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downcpudell.setText("▼");
        jPanel7.add(downcpudell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, 20));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CPUs");
        jLabel23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 40));

        cpudell.setEditable(false);
        cpudell.setBackground(new java.awt.Color(255, 255, 255));
        cpudell.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cpudell.setForeground(new java.awt.Color(51, 51, 51));
        cpudell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpudell.setText("0");
        cpudell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        cpudell.setFocusable(false);
        jPanel7.add(cpudell, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 195, 30, 30));

        graphicdell.setEditable(false);
        graphicdell.setBackground(new java.awt.Color(255, 255, 255));
        graphicdell.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        graphicdell.setForeground(new java.awt.Color(51, 51, 51));
        graphicdell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        graphicdell.setText("0");
        graphicdell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        graphicdell.setFocusable(false);
        jPanel7.add(graphicdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 245, 30, 30));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Graphic Card");
        jLabel24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 40));

        upgraphicdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upgraphicdell.setText("▲");
        jPanel7.add(upgraphicdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 70, 20));

        downgraphicdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downgraphicdell.setText("▼");
        jPanel7.add(downgraphicdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 70, 20));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Type of Worker");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel7.add(jProgressBar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, 20));
        jPanel7.add(jProgressBar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 100, 20));
        jPanel7.add(jProgressBar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, 20));
        jPanel7.add(jProgressBar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 100, 20));
        jPanel7.add(jProgressBar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 100, 20));

        assemdell.setEditable(false);
        assemdell.setBackground(new java.awt.Color(255, 255, 255));
        assemdell.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        assemdell.setForeground(new java.awt.Color(51, 51, 51));
        assemdell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        assemdell.setText("0");
        assemdell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        assemdell.setFocusable(false);
        jPanel7.add(assemdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 295, 30, 30));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Assemblers");
        jLabel26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 40));

        upassemdell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        upassemdell.setText("▲");
        jPanel7.add(upassemdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, 20));

        downassemadell.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        downassemadell.setText("▼");
        jPanel7.add(downassemadell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, 20));
        jPanel7.add(jProgressBar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 100, 20));

        mbdell.setEditable(false);
        mbdell.setBackground(new java.awt.Color(255, 255, 255));
        mbdell.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        mbdell.setForeground(new java.awt.Color(51, 51, 51));
        mbdell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mbdell.setText("0");
        mbdell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        mbdell.setFocusable(false);
        mbdell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbdellActionPerformed(evt);
            }
        });
        jPanel7.add(mbdell, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 45, 30, 30));

        jTextField35.setEditable(false);
        jTextField35.setBackground(new java.awt.Color(255, 255, 255));
        jTextField35.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField35.setForeground(new java.awt.Color(51, 51, 51));
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setText("0");
        jTextField35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField35.setFocusable(false);
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 45, 30, 30));

        jTextField36.setEditable(false);
        jTextField36.setBackground(new java.awt.Color(255, 255, 255));
        jTextField36.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField36.setForeground(new java.awt.Color(51, 51, 51));
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setText("0");
        jTextField36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField36.setFocusable(false);
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 145, 30, 30));

        jTextField37.setEditable(false);
        jTextField37.setBackground(new java.awt.Color(255, 255, 255));
        jTextField37.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField37.setForeground(new java.awt.Color(51, 51, 51));
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField37.setText("0");
        jTextField37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField37.setFocusable(false);
        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 245, 30, 30));

        jTextField38.setEditable(false);
        jTextField38.setBackground(new java.awt.Color(255, 255, 255));
        jTextField38.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField38.setForeground(new java.awt.Color(51, 51, 51));
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setText("0");
        jTextField38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField38.setFocusable(false);
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 195, 30, 30));

        jTextField39.setEditable(false);
        jTextField39.setBackground(new java.awt.Color(255, 255, 255));
        jTextField39.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField39.setForeground(new java.awt.Color(51, 51, 51));
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setText("0");
        jTextField39.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField39.setFocusable(false);
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 195, 30, 30));

        jTextField40.setEditable(false);
        jTextField40.setBackground(new java.awt.Color(255, 255, 255));
        jTextField40.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField40.setForeground(new java.awt.Color(51, 51, 51));
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField40.setText("0");
        jTextField40.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField40.setFocusable(false);
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 45, 30, 30));

        jTextField41.setEditable(false);
        jTextField41.setBackground(new java.awt.Color(255, 255, 255));
        jTextField41.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField41.setForeground(new java.awt.Color(51, 51, 51));
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setText("0");
        jTextField41.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField41.setFocusable(false);
        jTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField41ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 95, 30, 30));

        jTextField42.setEditable(false);
        jTextField42.setBackground(new java.awt.Color(255, 255, 255));
        jTextField42.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField42.setForeground(new java.awt.Color(51, 51, 51));
        jTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField42.setText("0");
        jTextField42.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField42.setFocusable(false);
        jTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField42ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 145, 30, 30));

        jTextField43.setEditable(false);
        jTextField43.setBackground(new java.awt.Color(255, 255, 255));
        jTextField43.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField43.setForeground(new java.awt.Color(51, 51, 51));
        jTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField43.setText("0");
        jTextField43.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField43.setFocusable(false);
        jTextField43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField43ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 195, 30, 30));

        jTextField44.setEditable(false);
        jTextField44.setBackground(new java.awt.Color(255, 255, 255));
        jTextField44.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField44.setForeground(new java.awt.Color(51, 51, 51));
        jTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField44.setText("0");
        jTextField44.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField44.setFocusable(false);
        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 245, 30, 30));

        jTextField45.setEditable(false);
        jTextField45.setBackground(new java.awt.Color(255, 255, 255));
        jTextField45.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField45.setForeground(new java.awt.Color(51, 51, 51));
        jTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField45.setText("0");
        jTextField45.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField45.setFocusable(false);
        jTextField45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField45ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 295, 30, 30));

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Max");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Standard");
        jLabel28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 80, 40));

        jTextField46.setEditable(false);
        jTextField46.setBackground(new java.awt.Color(0, 0, 0));
        jTextField46.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField46.setForeground(new java.awt.Color(255, 255, 255));
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField46.setText("0");
        jTextField46.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField46.setFocusable(false);
        jTextField46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField46ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 80, 30));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Standard");
        jLabel29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 80, 40));

        jTextField47.setEditable(false);
        jTextField47.setBackground(new java.awt.Color(0, 0, 0));
        jTextField47.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField47.setForeground(new java.awt.Color(255, 255, 255));
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField47.setText("0");
        jTextField47.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField47.setFocusable(false);
        jTextField47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField47ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 80, 30));

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Type of Worker");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Motherboard");
        jLabel31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 40));

        jTextField48.setEditable(false);
        jTextField48.setBackground(new java.awt.Color(255, 255, 255));
        jTextField48.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField48.setForeground(new java.awt.Color(51, 51, 51));
        jTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField48.setText("0");
        jTextField48.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jTextField48.setFocusable(false);
        jTextField48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField48ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 295, 30, 30));

        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Warehouse");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 570, 340));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Project Manager");
        jLabel33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 40));

        jTextField49.setEditable(false);
        jTextField49.setBackground(new java.awt.Color(255, 255, 255));
        jTextField49.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField49.setForeground(new java.awt.Color(51, 51, 51));
        jTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField49.setText("....");
        jTextField49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField49.setFocusable(false);
        jTextField49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField49ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 40));

        jTextField50.setEditable(false);
        jTextField50.setBackground(new java.awt.Color(255, 255, 255));
        jTextField50.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField50.setForeground(new java.awt.Color(51, 51, 51));
        jTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField50.setText("0");
        jTextField50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField50.setFocusable(false);
        jTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField50ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 70, 40));

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Fouls");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 70, 40));

        jTextField51.setEditable(false);
        jTextField51.setBackground(new java.awt.Color(255, 255, 255));
        jTextField51.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField51.setForeground(new java.awt.Color(51, 51, 51));
        jTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField51.setText("0");
        jTextField51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField51.setFocusable(false);
        jTextField51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField51ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 120, 40));

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Discounted");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 120, 40));

        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Proyect Manager");
        jLabel36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 150, 40));

        jTextField52.setEditable(false);
        jTextField52.setBackground(new java.awt.Color(255, 255, 255));
        jTextField52.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField52.setForeground(new java.awt.Color(51, 51, 51));
        jTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField52.setText("....");
        jTextField52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField52.setFocusable(false);
        jTextField52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField52ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, 40));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 360, 570, 160));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 780, 590));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Apple Computers 💻");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("DELL Computers 💻");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 420, -1));

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(0, 0, 0));
        jTextField16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("0");
        jTextField16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField16.setFocusable(false);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 150, 30));

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(255, 255, 255));
        jTextField24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextField24.setForeground(new java.awt.Color(51, 51, 51));
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("COUNTDOWN: ");
        jTextField24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField24.setFocusable(false);
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 20, 150, 30));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 70));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void downmbappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downmbappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downmbappleActionPerformed

    private void upmbappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upmbappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upmbappleActionPerformed

    private void ramappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramappleActionPerformed

    private void downramappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downramappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downramappleActionPerformed

    private void upramappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upramappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upramappleActionPerformed

    private void powerappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerappleActionPerformed

    private void uppowerappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppowerappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uppowerappleActionPerformed

    private void downpowerappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downpowerappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downpowerappleActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void mbappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbappleActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void downmbdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downmbdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downmbdellActionPerformed

    private void upmbdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upmbdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upmbdellActionPerformed

    private void ramdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramdellActionPerformed

    private void downramdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downramdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downramdellActionPerformed

    private void upramdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upramdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upramdellActionPerformed

    private void powerdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerdellActionPerformed

    private void uppowerdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppowerdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uppowerdellActionPerformed

    private void downpowerdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downpowerdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downpowerdellActionPerformed

    private void mbdellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbdellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbdellActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField41ActionPerformed

    private void jTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42ActionPerformed

    private void jTextField43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField43ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void jTextField45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField45ActionPerformed

    private void jTextField46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField46ActionPerformed

    private void jTextField47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField47ActionPerformed

    private void jTextField48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField48ActionPerformed

    private void jTextField49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField49ActionPerformed

    private void jTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField50ActionPerformed

    private void jTextField51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField51ActionPerformed

    private void jTextField52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField52ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BothGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assemapple;
    private javax.swing.JTextField assemdell;
    private javax.swing.JTextField cpuapple;
    private javax.swing.JTextField cpudell;
    private javax.swing.JButton downassemadell;
    private javax.swing.JButton downassemapple;
    private javax.swing.JButton downcpuapple;
    private javax.swing.JButton downcpudell;
    private javax.swing.JButton downgraphicapple;
    private javax.swing.JButton downgraphicdell;
    private javax.swing.JButton downmbapple;
    private javax.swing.JButton downmbdell;
    private javax.swing.JButton downpowerapple;
    private javax.swing.JButton downpowerdell;
    private javax.swing.JButton downramapple;
    private javax.swing.JButton downramdell;
    private javax.swing.JTextField graphicapple;
    private javax.swing.JTextField graphicdell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar11;
    private javax.swing.JProgressBar jProgressBar12;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField mbapple;
    private javax.swing.JTextField mbdell;
    private javax.swing.JTextField powerapple;
    private javax.swing.JTextField powerdell;
    private javax.swing.JTextField ramapple;
    private javax.swing.JTextField ramdell;
    private javax.swing.JButton upassemapple;
    private javax.swing.JButton upassemdell;
    private javax.swing.JButton upcpuapple;
    private javax.swing.JButton upcpudell;
    private javax.swing.JButton upgraphicapple;
    private javax.swing.JButton upgraphicdell;
    private javax.swing.JButton upmbapple;
    private javax.swing.JButton upmbdell;
    private javax.swing.JButton uppowerapple;
    private javax.swing.JButton uppowerdell;
    private javax.swing.JButton upramapple;
    private javax.swing.JButton upramdell;
    // End of variables declaration//GEN-END:variables
}
