/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

/**
 *
 * @author Sofia
 */
public class NewData extends javax.swing.JFrame {

    /**
     * Creates new form NewData
     */
    public NewData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Deadline = new javax.swing.JTextField();
        Motherboard_apple = new javax.swing.JTextField();
        RAM_memory_apple = new javax.swing.JTextField();
        Cpus_apple = new javax.swing.JTextField();
        Power_supply_apple = new javax.swing.JTextField();
        Graphic_apple = new javax.swing.JTextField();
        Motherboard_dell = new javax.swing.JTextField();
        RAM_dell = new javax.swing.JTextField();
        Cpus_dell = new javax.swing.JTextField();
        Power_supply_dell = new javax.swing.JTextField();
        Assembler_dell = new javax.swing.JTextField();
        Time_day = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Graphic_dell = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Assembler_apple = new javax.swing.JTextField();

        jTextField8.setText("jTextField1");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Valores iniciales de la Simulacion");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 80));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Motherboard:");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 102, 100, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dell:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 25, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apple:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 25, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("RAM Memory:");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 139, 100, -1));

        jLabel6.setBackground(new java.awt.Color(153, 204, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Motherboard:");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 102, 100, -1));

        jLabel7.setBackground(new java.awt.Color(153, 204, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CPUs:");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 173, 100, -1));

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("RAM Memory:");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 139, 100, -1));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Power supply:");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 205, 100, -1));

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CPUs:");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 173, 100, -1));

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Assembler");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 268, 100, -1));

        jLabel12.setBackground(new java.awt.Color(153, 204, 255));
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Power supply:");
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 205, 100, -1));

        jLabel13.setBackground(new java.awt.Color(153, 204, 255));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Deadline Time:");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 110, -1));

        jLabel14.setBackground(new java.awt.Color(153, 204, 255));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Graphic Card:");
        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 236, 100, -1));

        jLabel15.setBackground(new java.awt.Color(153, 204, 255));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Time of day:");
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 110, -1));

        Deadline.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Deadline.setText("0");
        Deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeadlineActionPerformed(evt);
            }
        });
        jPanel4.add(Deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 30, -1));
        Deadline.getAccessibleContext().setAccessibleName("");

        Motherboard_apple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Motherboard_apple.setText("0");
        Motherboard_apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Motherboard_appleActionPerformed(evt);
            }
        });
        jPanel4.add(Motherboard_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 103, 30, -1));

        RAM_memory_apple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAM_memory_apple.setText("0");
        jPanel4.add(RAM_memory_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 30, -1));

        Cpus_apple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cpus_apple.setText("0");
        jPanel4.add(Cpus_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 175, 30, -1));

        Power_supply_apple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Power_supply_apple.setText("0");
        Power_supply_apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Power_supply_appleActionPerformed(evt);
            }
        });
        jPanel4.add(Power_supply_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 206, 30, -1));

        Graphic_apple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Graphic_apple.setText("0");
        Graphic_apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Graphic_appleActionPerformed(evt);
            }
        });
        jPanel4.add(Graphic_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 237, 30, -1));

        Motherboard_dell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Motherboard_dell.setText("0");
        Motherboard_dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Motherboard_dellActionPerformed(evt);
            }
        });
        jPanel4.add(Motherboard_dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 103, 30, -1));

        RAM_dell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAM_dell.setText("0");
        RAM_dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAM_dellActionPerformed(evt);
            }
        });
        jPanel4.add(RAM_dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 30, -1));

        Cpus_dell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cpus_dell.setText("0");
        Cpus_dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cpus_dellActionPerformed(evt);
            }
        });
        jPanel4.add(Cpus_dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 174, 30, -1));

        Power_supply_dell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Power_supply_dell.setText("0");
        Power_supply_dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Power_supply_dellActionPerformed(evt);
            }
        });
        jPanel4.add(Power_supply_dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 207, 30, -1));

        Assembler_dell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Assembler_dell.setText("0");
        Assembler_dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assembler_dellActionPerformed(evt);
            }
        });
        jPanel4.add(Assembler_dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 30, -1));

        Time_day.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Time_day.setText("0");
        Time_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Time_dayActionPerformed(evt);
            }
        });
        jPanel4.add(Time_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 30, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 10, 300));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 820, 10));

        jLabel16.setBackground(new java.awt.Color(153, 204, 255));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Graphic Card:");
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 236, 100, -1));

        Graphic_dell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Graphic_dell.setText("0");
        Graphic_dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Graphic_dellActionPerformed(evt);
            }
        });
        jPanel4.add(Graphic_dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 30, -1));

        jLabel17.setBackground(new java.awt.Color(153, 204, 255));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Assembler");
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 268, 100, -1));

        Assembler_apple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Assembler_apple.setText("0");
        Assembler_apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assembler_appleActionPerformed(evt);
            }
        });
        jPanel4.add(Assembler_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 30, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 820, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeadlineActionPerformed

    private void Power_supply_appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Power_supply_appleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Power_supply_appleActionPerformed

    private void Graphic_appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Graphic_appleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Graphic_appleActionPerformed

    private void Motherboard_dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Motherboard_dellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Motherboard_dellActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void RAM_dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAM_dellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAM_dellActionPerformed

    private void Cpus_dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cpus_dellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cpus_dellActionPerformed

    private void Power_supply_dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Power_supply_dellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Power_supply_dellActionPerformed

    private void Assembler_dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assembler_dellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Assembler_dellActionPerformed

    private void Time_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Time_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Time_dayActionPerformed

    private void Motherboard_appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Motherboard_appleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Motherboard_appleActionPerformed

    private void Graphic_dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Graphic_dellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Graphic_dellActionPerformed

    private void Assembler_appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assembler_appleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Assembler_appleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Assembler_apple;
    private javax.swing.JTextField Assembler_dell;
    private javax.swing.JTextField Cpus_apple;
    private javax.swing.JTextField Cpus_dell;
    private javax.swing.JTextField Deadline;
    private javax.swing.JTextField Graphic_apple;
    private javax.swing.JTextField Graphic_dell;
    private javax.swing.JTextField Motherboard_apple;
    private javax.swing.JTextField Motherboard_dell;
    private javax.swing.JTextField Power_supply_apple;
    private javax.swing.JTextField Power_supply_dell;
    private javax.swing.JTextField RAM_dell;
    private javax.swing.JTextField RAM_memory_apple;
    private javax.swing.JTextField Time_day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
